# Generated by Django 4.2.7 on 2023-11-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0002_wordlesubmission_clap_reactions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordlesubmission",
            name="clap_reactions",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="wordlesubmission",
            name="mind_blown_reactions",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="wordlesubmission",
            name="monkey_reactions",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="wordlesubmission",
            name="sad_reactions",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="wordlesubmission",
            name="wow_reactions",
            field=models.IntegerField(default=0),
        ),
    ]
