# Generated by Django 4.2.7 on 2023-11-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0003_alter_wordlesubmission_clap_reactions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordlesubmission",
            name="submission_text",
            field=models.TextField(max_length=200),
        ),
    ]
