# Generated by Django 3.2 on 2023-11-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_wordlesubmission_submission_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlesubmission',
            name='submission_text',
            field=models.CharField(max_length=200),
        ),
    ]
