# Generated by Django 4.2.7 on 2023-11-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0005_alter_wordlesubmission_submission_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordlesubmission",
            name="submission_text",
            field=models.TextField(max_length=200),
        ),
    ]
