# Generated by Django 4.2.7 on 2023-12-01 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0006_alter_wordlesubmission_submission_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Champion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("window_type", models.CharField(max_length=30)),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                ("num_guesses", models.IntegerField()),
                ("num_possible_guesses", models.IntegerField()),
                (
                    "submitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.submitter",
                    ),
                ),
            ],
        ),
    ]
