# Generated by Django 3.2 on 2022-10-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('token_memo', models.CharField(max_length=200)),
                ('token_used', models.BooleanField(default=True)),
                ('token_revoked', models.BooleanField(default=False)),
            ],
        ),
    ]
